### ISSUE TITLE
install script issues

### ISSUE THREAD

**Issue by g7ruh** [dylski/PaperPiAI#1]
hi @dylski 

I am awaiting a inky screen, hopefully arrives tomorrow :)

I have run the install.sh on a Pi 4 to test. Using bullseye not bookworm.

I cannot find the generate_picture.py or display_picture.py files anywhere after the install. Are they copied somewhere? I cannot find them.
Obviously, I can download them from src directory on github. Suggestion: add that to the install.sh.

A thought / enhancement: on a Pi 4 it takes a long time to install. Could you consider modifying the script for cmake to use more than 1 core? It does go a lot faster when using an SD card. I re-ran it with:

`cmake --build .  --config Release -- -j4`

and it goes a lot faster. cmake appears to have an --all option to use all available cores. Maybe you could add a how many CPUs to use or a use all cores as a script option to allow the user to select?

The last step `Filtering content: 100% (2640/2640)`
takes a long time: is that just a function of the CPU speed or can it be speeded up by using more cores?

I will test using bookworm when I have it working on bullseye.

Thanks for your help

regards
Roger G7RUH

**Comment by dylski** [comment]
Thanks for the feedback.
The install.sh just installs everything you need to run the scripts so yes, just copy the `src` scripts wherever you like and run them using the python you pip installed everything else to.

I forgot to say in the README to start by cloning the repo.

You'll probably also want to edit the paths in `generate_picture.py` to point to where the your stable diffusion build is (e.g. `OnnxStream\src\build\sd`) and model is.

I'll also check the `--all` flag for compilation on the Zero and might add that to the script. 

re. filtering content - I don't know anything about that. In all the whole install process took about 3 hours on my RPi-Zero.

I'll update the README with this information.

**Comment by g7ruh** [comment]
Thank you for the swift response.

I was thinking about those with limited python skills, maybe adding the copy of src scripts to the install.sh will help those who have construction skills but not computing skills. It would help give a working "out of the box" experience for novice python users.

With my Pi4 4GB time ./install.sh with -j4 gave:

real    47m41.005s
user    77m19.046s
sys     17m47.288s

I will try the same on the Pi ZW2 and report back.

I saw your creation on Tom's Hardware https://www.tomshardware.com/raspberry-pi/raspberry-pi-zero-2-w-uses-ai-to-make-infinite-flower-paintings-on-an-e-ink-display and thought: Ah! a Christmas present for somebody.

regards
Roger G7RUH
