### ISSUE TITLE
Run time script errors

### ISSUE THREAD

**Issue by g7ruh** [dylski/PaperPiAI#2]
Hi @dylski 

I have successfully installed the software and have it running. I am impressed with what a low-end Pi can do. Well done. I used Bullseye lite and installed on a Pi 4 then tested on the Zero 2 W with screen. I will test using Bookworm lite soon. 

A few issues:

1) I have yet to get it to compile on the Zero 2 W. I am working on it. Having set swap = 256, it did hang the first time without -- -j4. Not sure why. Trouble is, it takes a while to test.

2) The multi core string for compile will not work on the Zero 2 W. Not enough memory and spends time going to swap file. The use of -- -j4 works on e.g. a Pi4 and speeds up the process a little. I suggest you note that in the Read.me

3) in src/generate_picture.py there are some errors so it will not run as is. See i) and ii) below:

`# Set the paths
installed_dir = "/home/dylski/Projects/PaperPiAI"
installed_dir = "./"
sd_bin = f"{installed_dir}/OnnxStream/src/build/sd"
#sd_model = f"{installed_dir}/stable_diffusion_models/stable-diffusion-xl-turbo-1.0-onnxstream"
sd_model = f"{installed_dir}/models/stable-diffusion-xl-turbo-1.0-onnxstream"
`

i) the line installed_dir = "./" should be deleted
ii) the path to model dir should be "/models/stable...."  not as in the original line above commented out
iii) Maybe a comment in the file below "#Set the paths " to tell the user to change the line below to their own install path. It makes it easier to find if you are not familiar with script files.

4) The Zero 2 W really needs a heat sink. It runs hot without and I suspect it may get hot enough to throttle during the "decode" phase. I added cooling before it got there in my test. I will test some more. I have another Zero 2 W with a glued on heatsink and will test using that when it is not being used elsewhere.

5) Just as a matter of interest, A Pi 5 will generate a picture in about 5 minutes. I was curious enough to try it.

Regards
Roger G7RUH

**Comment by dylski** [comment]
That's great to hear and thanks for the feedback. 

1. Maybe you need to set the swap larger. I actually had it set to 2GB but noticed that it never seemed to exceed 200MB hence my recommendation of setting it to 256MB. It's possible that it could have had brief spikes that I didn't notice. I'll update the recommendation to what I know to work, i.e. 2GB.

2. Good to know.

3. I'd already updated the README to say that install_dir needs to be edited to point to the installation. I'll add a comment in the script saying that too.

4. I've found it maxes out at 70°C - my room temperature was ~21°C - which seemed okay to me but agreed if it's in a hot area or confined space them a heat sink might be useful.

5. Indeed - I did most of my discovering good style prompts my my RPi5 :-)

**Comment by g7ruh** [comment]
thanks for response,

one more thing: Bullseye lite and Bookworm lite do not have git installed so before the clone line you need a "sudo apt install git"

I will try the 256 MB swap and then increase if it fails.

Question re temperature, the way the screen is by default the GPIO connector is above the CPU / CPU+heatsink. Given that hot air rises, is it possble to rotate the screen 180 degrees and then mount the screen 'upside down' in the frame? It may help in a hot environment.

Another observation, using a 32GB sd card, there is not too much left, about 75% used. Given that filling a disk near maximum is not a good thing, if pictures are not deleted that could cause a problem over time. Maybe worth mentioning it as a caution?

Regards
Roger G7RUH

**Comment by dylski** [comment]
Hi Roger, 

I've added info about install git now.

Re mounting upside down - my concern would be the cable coming out the top putting weird forces on the RPi. 
Nevertheless, if needs be, to rotate the image 180 degrees you can add 

`image = cv2.rotate(image, cv2.ROTATE_180)`

to the [display function](https://github.com/dylski/PaperPiAI/blob/main/src/display_picture.py#L81).

I've also added a mention about storage in the README. FWIW, I estimate that if you have 8GB free and are generating an image every 24 hours then you should be okay for the next 28 years :-)

**Comment by g7ruh** [comment]
> every 24 hours then you should be okay for the next 28 years :-)

Now that made me smile! Maybe you should add an auto warning after 26 years, just in case :-)


Yes, the cable at the top v at the bottom. the micro USB cables are fairly flexible, but having a small HDMI adapter to a "full fat" HDMI connector will likely strain the PCB solder joints.... would not want to go there. Right angle HDMI connectors are available, not sure about the small ones having 90 degree adaptors. All a bit mute, running a monitor cable out of your picture frame.... No! I do not think so.

Regards,
Roger G7RUH
