### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Ads1710** [dylski/PaperPiAI#5]
Hi there,

I first want to say what a fantastic project this is. It is interesting, and I was keen to try it out. However, whenever I have tried to run the code, even after fresh installs, I keep running into this error. Could anybody point me in the direction of how to resolve it?

```
ads17@picturepi:~ $ python PaperPiAI/src/generate_picture.py /tmp
Creating image with prompt 'single bluebell stem as a cartoon drawing'
Using seed 8541
Saving to /tmp/single_bluebell_stem_as_a_cartoon_drawing_seed_8541_steps_5.png
Running command:
['/home/ads17//OnnxStream/src/build/sd', '--xl', '--turbo', '--models-path', '/home/ads17//models/stable-diffusion-xl-turbo-1.0-onnxstream', '--rpi-lowmem', '--prompt', 'single bluebell stem as a cartoon drawing', '--seed', '8541', '--output', '/tmp/single_bluebell_stem_as_a_cartoon_drawing_seed_8541_steps_5.png', '--steps', '5']
----------------[start]------------------
positive_prompt: single bluebell stem as a cartoon drawing
SDXL turbo doesn't support negative_prompts
output_png_path: /tmp/single_bluebell_stem_as_a_cartoon_drawing_seed_8541_steps_5.png
steps: 5
seed: 8541
----------------[prompt]------------------
Token: "single</w>"
Token: "blue"
Token: "bell</w>"
Token: "stem</w>"
Token: "as</w>"
Token: "a</w>"
Token: "cartoon</w>"
Token: "drawing</w>"
=== ERROR === DiskPrefetchWeightsProvider::provide: fatal error in worker thread: "read_file: unable to open file (/home/ads17//models/stable-diffusion-xl-turbo-1.0-onnxstream/sdxl_text_encoder_2_fp32/te2_2E_text_5F_model_2E_encoder_2E_layers_2E_4_2E_self_5F_attn_2E_q_5F_proj_2E_bias.bin).".
Command executed successfully.
Traceback (most recent call last):
  File "/home/ads17/PaperPiAI/src/generate_picture.py", line 90, in <module>
    shutil.copyfile(fullpath, shared_fullpath)
  File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/single_bluebell_stem_as_a_cartoon_drawing_seed_8541_steps_5.png'
```

**Comment by dylski** [comment]
Thanks!

The problem seems that it can't find one of the model files. 
Maybe the model files are somewhere else or not all of them downloaded.

Check that the model files are where you are telling it they should be, i.e. in `/home/ads17//models/stable-diffusion-xl-turbo-1.0-onnxstream`.

The specific file that it's complaining about is `/home/ads17//models/stable-diffusion-xl-turbo-1.0-onnxstream/sdxl_text_encoder_2_fp32/te2_2E_text_5F_model_2E_encoder_2E_layers_2E_4_2E_self_5F_attn_2E_q_5F_proj_2E_bias.bin` so check that it's there.

I don't think the double '/' before 'models' should be an issue but you might want to remove the '/' from the end of the path in your `install_dir`anyway.

**Comment by Ads1710** [comment]
Thanks for the reply. Oddly the files or at least this file seems to be there
``
ads17@picturepi:~ $ ls /home/ads17/models/stable-diffusion-xl-turbo-1.0-onnxstream/sdxl_text_encoder_2_fp32/te2_2E_text_5F_model_2E_encoder_2E_layers_2E_4_2E_self_5F_attn_2E_k_5F_proj_2E_bias.bin
/home/ads17/models/stable-diffusion-xl-turbo-1.0-onnxstream/sdxl_text_encoder_2_fp32/te2_2E_text_5F_model_2E_encoder_2E_layers_2E_4_2E_self_5F_attn_2E_k_5F_proj_2E_bias.bin
``

So I am not too sure and even when I change the double '/' to just a single '/', I still run into the same issue
```
ads17@picturepi:~ $ python PaperPiAI/src/generate_picture.py /tmp
Creating image with prompt 'gardenia blossom as a vintage retro illustration'
Using seed 2110
Saving to /tmp/gardenia_blossom_as_a_vintage_retro_illustration_seed_2110_steps_5.png
Running command:
['/home/ads17/OnnxStream/src/build/sd', '--xl', '--turbo', '--models-path', '/home/ads17/models/stable-diffusion-xl-turbo-1.0-onnxstream', '--rpi-lowmem', '--prompt', 'gardenia blossom as a vintage retro illustration', '--seed', '2110', '--output', '/tmp/gardenia_blossom_as_a_vintage_retro_illustration_seed_2110_steps_5.png', '--steps', '5']
----------------[start]------------------
positive_prompt: gardenia blossom as a vintage retro illustration
SDXL turbo doesn't support negative_prompts
output_png_path: /tmp/gardenia_blossom_as_a_vintage_retro_illustration_seed_2110_steps_5.png
steps: 5
seed: 2110
----------------[prompt]------------------
Token: "garden"
Token: "ia</w>"
Token: "blossom</w>"
Token: "as</w>"
Token: "a</w>"
Token: "vintage</w>"
Token: "retro</w>"
Token: "illustration</w>"
=== ERROR === DiskPrefetchWeightsProvider::provide: fatal error in worker thread: "read_file: unable to open file (/home/ads17/models/stable-diffusion-xl-turbo-1.0-onnxstream/sdxl_text_encoder_2_fp32/te2_2E_text_5F_model_2E_encoder_2E_layers_2E_4_2E_self_5F_attn_2E_q_5F_proj_2E_bias.bin).".
Command executed successfully.
Traceback (most recent call last):
  File "/home/ads17/PaperPiAI/src/generate_picture.py", line 90, in <module>
    shutil.copyfile(fullpath, shared_fullpath)
  File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gardenia_blossom_as_a_vintage_retro_illustration_seed_2110_steps_5.png'
```

So, I'm going to run another fresh install and try again. Maybe something corrupted during the process, so I'll give it another go and see what happens.

**Comment by dylski** [comment]
That is indeed odd. Maybe also check the permissions are correct and it's the right size? Here are the details in my copy:

`-rw-r--r-- 1 dylski dylski 5120 Dec  1 00:38 models/stable-diffusion-xl-turbo-1.0-onnxstream/sdxl_text_encoder_2_fp32/te2_2E_text_5F_model_2E_encoder_2E_layers_2E_4_2E_self_5F_attn_2E_k_5F_proj_2E_bias.bin`

**Comment by Ads1710** [comment]
For some reason, after reinstalling twice, it works now, but thank you for your help! Fantastic project, and I can't wait to see what you make next
